# Generated by Django 3.2.8 on 2021-12-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('txn_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('email_or_mobile', models.TextField(default='')),
                ('otp', models.CharField(max_length=10)),
                ('expire_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'otp',
            },
        ),
    ]
