# Generated by Django 3.2.8 on 2021-12-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='email',
            field=models.EmailField(blank=True, max_length=10, null=True),
        ),
    ]
