# Generated by Django 3.2.8 on 2021-12-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20211224_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='password_token',
            field=models.CharField(default=1, editable=False, max_length=2000),
            preserve_default=False,
        ),
    ]
