# Generated by Django 3.2.8 on 2021-12-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_cuser_password_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuser',
            name='password_token',
        ),
    ]
